module i11eperf {
  /* The "ts" field stores a time stamp and is used in lieu of the DDS source timestamp
     for two reasons:

     - Fast-DDS doesn't support write_w_timestamp

     - All variants have different ideas of the representation of a time stamp,
       this avoids the need for different conversions in the different cases */

  @topic
  struct ou {
    unsigned long long ts;
    unsigned long s;
  };

  @topic
  struct a32 {
    unsigned long long ts;
    unsigned long s;
    octet xary[32 - 12];
  };

  @topic
  struct a128 {
    unsigned long long ts;
    unsigned long s;
    octet xary[128 - 12];
  };

  @topic
  struct a1024 {
    unsigned long long ts;
    unsigned long s;
    octet xary[1024 - 12];
  };

  @topic
  struct a48k {
    unsigned long long ts;
    unsigned long s;
    octet xary[48*1024 - 12];
  };

  @topic
  struct a64k {
    unsigned long long ts;
    unsigned long s;
    octet xary[64*1024 - 12];
  };

  @topic
  struct a1M {
    unsigned long long ts;
    unsigned long s;
    octet xary[1024*1024 - 12];
  };

  @topic
  struct seq {
    unsigned long long ts;
    unsigned long s;
    sequence<octet> xseq;
  };
};
